apiVersion: apps/v1
kind: Deployment
metadata:
  name: xrdp
  namespace: infra
  labels:
    app: xrdp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xrdp
  template:
    metadata:
      labels:
        app: xrdp
    spec:
      containers:
      - name: xrdp
        image:  shotofw/xrdp:8
        ports:
        - containerPort: 3389


